version: '3'
services:
  server:
    build: ./server
    depends_on:
      - "db"
    ports:
      - "80:8080"
    entrypoint: ./wait-for-it.sh db:3306 -- ./server
  db:
    build: ./database
    container_name: my_db
    volumes:
      - ./database/data:/var/lib/mysql
    ports:
      - "3306:3306"
